# Generated by Django 4.2.7 on 2023-11-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_alter_course_options_alter_lesson_options_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма оплаты'),
        ),
    ]
